name: Container Tests

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]
  workflow_dispatch:

env:
  IMAGE_TAG: utility-ci:${{ github.sha }}

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - name: Build Docker image for tests
        id: build-image
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7.0.0
        with:
          context: .
          push: false
          load: true
          tags: ${{ env.IMAGE_TAG }}
          secrets: |
            github_token=${{ github.token }}

      - name: Run container tests
        uses: plexsystems/container-structure-test-action@c0a028aa96e8e82ae35be556040340cbb3e280ca # v0.3.0
        with:
          image: ${{ env.IMAGE_TAG }}
          config: ./container-tests.yaml
