name: Container Tests

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]
  workflow_dispatch:

env:
  IMAGE_TAG: utility-ci:${{ github.sha }}

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - name: Build Docker image for tests
        id: build-image
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: .
          push: false
          load: true
          tags: ${{ env.IMAGE_TAG }}
          secrets: |
            github_token=${{ github.token }}

      - name: Run container tests
        uses: plexsystems/container-structure-test-action@c0a028aa96e8e82ae35be556040340cbb3e280ca # v0.3.0
        with:
          image: ${{ env.IMAGE_TAG }}
          config: ./container-tests.yaml
